---

# Playbook to provision single application server

- name: Bootstrap instances
  hosts: app_servers
  gather_facts: no
  become: true
  roles:
    - python

- name: Deploy edxapp and related services
  hosts: app_servers
  become: True
  gather_facts: True
  vars:
    migrate_db: "no"  # Not really needed, but here for extra security
  roles:
    - role: swapfile
      SWAPFILE_SIZE: 4GB
    - role: nginx
      nginx_sites:
      - cms
      - lms
      - forum
      nginx_default_sites:
      - lms
      tags:
        - edxapp_nginx
    - role: edxapp
    - forum
    - role: aws
      when: COMMON_OBJECT_STORE_LOG_SYNC
