---

# Inisghts and analytics-api Deployment:

- name: Bootstrap instances
  hosts: all
  gather_facts: no
  become: true
  roles:
    - python

- name: Configure analytics servers
  hosts: insights_servers
  become: True
  gather_facts: True
  roles:
    - role: swapfile
      SWAPFILE_SIZE: 2GB
    - role: nginx
      nginx_sites:
        - insights
      nginx_default_sites:
        - insights
    - insights
    - analytics_api
